name: Build
on: [ push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
      - name: 'Set up Node.js and dependencies'
        uses: ./.github/actions/set-up
      - name: 'Build'
        run: pnpm build
